# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'derucciTS' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for derucciTS
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
    'RCTImage'
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/lib/ios'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  
  pod 'JPush'


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end


end

